[[plugins]]                                    
repo = 'Shougo/dein.vim' 

[[plugins]]                                    
repo = 'Shougo/denite.nvim'                                          
hook_add='''
  source ~/.config/nvim/denite.vim
'''

# [[plugins]]
# repo = 'prabirshrestha/vim-lsp'

# [[plugins]]
# repo = 'mattn/vim-lsp-settings'

#  [[plugins]]
#  repo = 'mattn/vim-lsp-icons'

[[plugins]]
repo = 'hrsh7th/vim-vsnip'

[[plugins]]
repo = 'hrsh7th/vim-vsnip-integ'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'

[[plugins]]                                    
repo = 'Shougo/neosnippet.vim'                                          

[[plugins]]                                    
repo = 'Shougo/neosnippet-snippets'                                          

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertCharPre'
hook_source = '''
  source ~/.config/nvim/deoplete.vim
'''
on_i = 1

[[plugins]]
repo = 'kristijanhusak/defx-git'
hook_add = '''
  source ~/.config/nvim/defx-git.vim
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = '''
  source ~/.config/nvim/defx.vim
'''

[[plugins]]                                    
repo = 'dracula/vim'                                          
name = 'dracula'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
  git checkout release
'''
hook_add = '''
  source ~/.config/nvim/coc.vim
'''

[[plugins]]                                    
repo = 'altercation/vim-colors-solarized'
name = 'solarized'

