# dein
[[plugins]]                                    
repo = 'Shougo/dein.vim' 

# denite
[[plugins]]                                    
repo = 'Shougo/denite.nvim'                                          
hook_add='''
  source ~/.config/nvim/denite.vim
'''

# defx
[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['defx-git', 'defx-icons']
hook_add = '''
  source ~/.config/nvim/defx.vim
'''
[[plugins]]
repo = 'kristijanhusak/defx-git'
hook_add = '''
  source ~/.config/nvim/defx-git.vim
'''
[[plugins]]
repo = 'kristijanhusak/defx-icons'
depends = ['vim-devicons']
[[plugins]]
repo = 'ryanoasis/vim-devicons'

# display function signatures
# [[plugins]]
# repo = 'shougo/echodoc.vim'
# hook_add = '''
#   source ~/.config/nvim/echodoc.vim
# '''


# [[plugins]]
# repo = 'lighttiger2505/deoplete-vim-lsp'

# [[plugins]]                                    
# repo = 'Shougo/neosnippet.vim'                                          

# [[plugins]]                                    
# repo = 'Shougo/neosnippet-snippets'                                          

#  [[plugins]]
#  repo = 'Shougo/deoplete.nvim'
#  on_event = 'InsertCharPre'
#  hook_source = '''
#    source ~/.config/nvim/deoplete.vim
#  '''
#  on_i = 1

# # for Golang
# [[plugins]]                                    
# repo = 'fatih/vim-go' 

# Coc
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
build = '''
  git checkout release
'''
hook_add = '''
  source ~/.config/nvim/coc.vim
'''

# comment
[[plugins]]
repo = 'tpope/vim-commentary'

# status bar
[[plugins]]
repo = 'vim-airline/vim-airline'
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# React Highliting
[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

# color scheme
[[plugins]]
repo = 'cocopon/iceberg.vim'                                          
hook_add = '''
  colorscheme iceberg
  source ~/.config/nvim/colorscheme.vim
'''
[[plugins]]
repo = 'gkeep/iceberg-dark'                                          
hook_add = '''
  let g:lightline = {'colorscheme': 'icebergDark'}
  let g:airline_theme='icebergDark'
'''
# [[plugins]]
# repo = 'dracula/vim'
# name = 'dracula'
# hook_add = '''
#   colorscheme dracula
#   source ~/.config/nvim/colorscheme.vim
# '''

# closing bracket complement
[[plugins]]                                    
repo = 'cohama/lexima.vim' 

# emmet
[[plugins]]
repo = 'mattn/emmet-vim'

# cheatsheet
[[plugins]]
repo = 'reireias/vim-cheatsheet'
hook_add = '''
  let g:cheatsheet#cheat_file = '~/.config/nvim/cheatsheet.md'
'''

# tag closing
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
  source ~/.config/nvim/vim-closetag.vim
'''

# [[plugins]] # lint tool
# repo = 'dense-analysis/ale'
# hook_add = '''
#   source ~/.config/nvim/ale.vim
# '''

# markdown
[[plugins]]
repo = 'godlygeek/tabular'
[[plugins]]
repo = 'plasticboy/vim-markdown'
depends = ['tabular']
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = '''
  'sh -c "cd app && yarn install"'
'''

# XtermColorTable
[[plugins]]
repo = 'guns/xterm-color-table.vim'

